language: go
go:
  - 1.8

install:
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/golang/dep/...
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide

script:
  - cd src/document && glide install
  - cd src/document && goose up
  - cd src/document && go build main.go
