language: go
go:
  - 1.8.1
env:
  - GOPATH: $HOME/$TRAVIS_REPO_SLUG
  - PATH: $PATH:$GOPATH/bin
  - DOCUMENT_ENV: test
  - GO15VENDOREXPERIMENT: 1

install:
  - go get -u github.com/Masterminds/glide

script:
  - ls -a
  - pwd
  - cd src/document && glide install
  - cd src/document && go build main.go
